// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6JAqScpO40S9j_TnyPYRT8cKIwy-pDoM',
    appId: '1:379955099923:web:6ba9cfbae67ea33e9842e6',
    messagingSenderId: '379955099923',
    projectId: 'pulse-5b489',
    authDomain: 'pulse-5b489.firebaseapp.com',
    storageBucket: 'pulse-5b489.firebasestorage.app',
    measurementId: 'G-KRVW157H96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR9pK-fl3556aoI-j_WTC1WcJ3ToE5rMM',
    appId: '1:379955099923:android:0db17bfbfcaa04189842e6',
    messagingSenderId: '379955099923',
    projectId: 'pulse-5b489',
    storageBucket: 'pulse-5b489.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr9bpxsUonLlKlX23NyKu53TGqbdnVcFo',
    appId: '1:379955099923:ios:a5c7a29638b5053b9842e6',
    messagingSenderId: '379955099923',
    projectId: 'pulse-5b489',
    storageBucket: 'pulse-5b489.firebasestorage.app',
    iosBundleId: 'com.example.safebunkV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr9bpxsUonLlKlX23NyKu53TGqbdnVcFo',
    appId: '1:379955099923:ios:a5c7a29638b5053b9842e6',
    messagingSenderId: '379955099923',
    projectId: 'pulse-5b489',
    storageBucket: 'pulse-5b489.firebasestorage.app',
    iosBundleId: 'com.example.safebunkV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6JAqScpO40S9j_TnyPYRT8cKIwy-pDoM',
    appId: '1:379955099923:web:21fd78e73f9c8b5b9842e6',
    messagingSenderId: '379955099923',
    projectId: 'pulse-5b489',
    authDomain: 'pulse-5b489.firebaseapp.com',
    storageBucket: 'pulse-5b489.firebasestorage.app',
    measurementId: 'G-FJ5KBLRXWM',
  );
}
